### PR TITLE
feat: docker house keeping

### PR DESCRIPTION
**Pull request by polaroidkidd**
* ~add specific docker network to allow gateway and subnet configuration~
  * add separate location for pgAdmin in dev mode
  * add docker container names attribute in addition to service name
  * add websocket config to nginx.conf from nginx.raw
  * ~make network-name configurable~

### CODE REVIEW

**Comment by polaroidkidd** [comment]
I'm noticing some differences between the docker-compose raw files and the docker-compose files. Which one servers as the "master"?

**Comment by polaroidkidd** [comment]
and why are we using different DBs in development vs Production? Currently the home for pgadmin is set to `$HOME`. Is this on purpose?

**Comment by derneuere** [comment]
I am not sure which use case you are trying to solve by allowing for subnet and gateway configuration in production? Usually this just works ™️ 😄 

As I understand this, you need this for your dev environment, but I don't really understand why a user who just wants to use it has to configure both subnet and gateway and why he would care to set this.

**Comment by polaroidkidd** [comment]
> subnet and gateway configuration in production

You're right, this is more of a dev thing, although there's no harm in having it in production mode (I ... think? :sweat_smile: ) In development mode it solves the problem of having to manually set the proxy in the `package.json` file for the frontend. If I currently want to develop for the frontend I have two options

 1) Develop from inside the docker container using the VS Code extension. This means that I have to either keep the locally built images or rebuild them every time I head into development mode.
 2) If I'm not in vscode, I start up the docker-compose.yaml file and use the `dev` tag for proxy & backend, then checkout which ip docker assigned to the proxy container, enter that and the port of choice into the `package.json`'s proxy configuration and exec `npm run start`

This PR would enable me to get up and running with frontend development easier and I'm not forced to build the dev containers.
  1) Checkout librephotos-docker
  2) Start up `docker-compose.yaml` (in it's current form with the gateway defined)
  3) Checkout librephotos-frontend
  4) exec `npm install` & `npm run start`

I appreciate the ease with which I can develop within vs-code, but if I'm not in that cosmos, getting up and running isn't as straight-forward (to me al least). Maybe it would be possible to support both modes of development? When you open librephotos-docker within vscode, you build the local images etc., but when you're using some other tool you can either use the locally built docker containers _or_ develop against the existing `dev` tags. 

> pgAdmin

Ah, ok. Currently the path for pgAdmin is set in the [user's home directory (`$Home`)](https://github.com/LibrePhotos/librephotos-docker/pull/46/files#diff-45db775cda5648eed0b607246e8ebd8d3c10dd07004f41cc26dbcc3d95c815e3L66). This mounts it to a local volume, but could be a docker-volme as well. I'm not sure how persistent this should be since I have no contact with it. I just know that I got curious when docker added a `pgAdmin` folder to my home directory. Took me a while to figure out it was coming from this project.


**naming**
The naming changes just expand on 20b774176779e95a76addadde2aa98733d213427. Changing the service names in the docker-compose configuration isn't enough to have those names pop up when using `docker ps` (They're still called something like `librephotos-docker_proxy_1` when they should be following the supplied names)

**Comment by derneuere** [comment]
Okay, thanks for the explanation 👍 

I am fine with the subnet and gateway variables in dev, but I will just get a lot of support questions from regular people if we add this also to prod. And please move the env variables to the dev part of the file 😄 

Naming and adding an explicit folder for pgAdmin is also good with me.

**Comment by polaroidkidd** [comment]
I thought about it and it occured to me that in all my time of selfhosting I've never actually had much use for defining a network :sweat_smile: I removed that part.

What remains is

  * expand renaming of services to `container_name` attribute
  * change default pgAdmin location to a directory inside the default directory (`pgAdminLocation=./librephotos/pgadmin`)

**Comment by derneuere** [comment]
Only small stuff, but then I can merge it 👍

**Comment by polaroidkidd** [comment]
Is there something else I should do here?

**Pull request merged**
