### PR TITLE
workaround for setup screen

### PR DESCRIPTION
**Pull request by Nerodacles**

### CODE REVIEW

**Comment by DigitalWarrior** [comment]
Awaiting input from sickelap regarding the changes he made. 
See issue https://github.com/LibrePhotos/librephotos/issues/702

**Comment by Nerodacles** [comment]
I did test it, and it works, but it just hangs a little bit on the "login screen" until the backend comes up.

**Comment by derneuere** [comment]
It makes sense to have a default in the e2e environment, but not for the regular environment, I think.

**Comment by DigitalWarrior** [comment]
I agree, want to get the devs input though.

**Comment by Nerodacles** [comment]
> It makes sense to have a default in the e2e environment, but not for the regular environment, I think.

Ok, doing it!

**Comment by Nerodacles** [comment]
It now has the admin user and pass. in the e2e.

**Comment by sickelap** [comment]
It was a mistake on my side to update the production docker-compose.yml

I've tested the changes and the solution is to set all ADMIN_* env vars to empty string by default in `docker-compose.raw` e.g., `ADMIN_EMAIL=${adminEmail:-}` and so on. The reason for having values set is to allow use .env file where admin* variables are set. And empty values are to get rid of warnings when starting the stack about undefined variables.

I noticed that I missed to set default value for `HEAVYWEIGHT_PROCESS`. While there, could you please set the default value for this one to empty string as well (same way as it's done in `docker-compose.e2e.raw`

**Comment by Nerodacles** [comment]
On it!

**Review by sickelap — APPROVED** [review]
Looks good. Thanks!

**Comment by Nerodacles** [comment]
> Looks good. Thanks!

No prob! im here to help.

**Pull request merged**
