### PR TITLE
arm and install instructions update

### PR DESCRIPTION
**Pull request by DigitalWarrior**
Added new yml reflecting arm. 
Edit readme.md to point install instructions from LibrePhotos.docs repo.

### CODE REVIEW

**Comment by derneuere** [comment]
I like the idea, but I think we should also implement some CI to build docker images for arm under the reallibrephotos organization, or? I found something like this that uses docker-buildx: https://medium.com/swlh/using-github-actions-to-build-arm-based-docker-images-413a8d498ee

We should also add the docker build file for arm.

**Comment by DigitalWarrior** [comment]
I agree that reallibrephotos organization should be hosing the arm images. I am not sure how radicand has it set up to be built. It would be great if github could do the auto actions for both. For now the arm.yml point to his dockerhub till we get it sorted out. Side note he has got the helm charts for kubernetes cluster just about ready. Going to have install docs this week and hopefully a push to librephotos-docker repo with the code.

**Comment by derneuere** [comment]
I think he just build the images locally and uploads them :D

**Comment by derneuere** [comment]
I will merge this pull request and open up a couple of new issues.

**Pull request merged**
